# Site settings
title: 夏海比比 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "关于设计与摄影，一个95后的个人博客"  # 一句话描述你的博客
baseurl: ""
url: "http://www.ba7khk.com"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "XIAHIBB" # 填写作者信息：名字
  email: xiahibb@gmail.com # 填写作者信息：邮箱
  bio: "XIAHIBB在黑暗的设计中探索自己的未来，目前从事的是品牌LOGO的设计。" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.ico # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.ioc # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username:   
github_username: xiahibb
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "XIAHIBB" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments : 
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-126330089-2" # 填写你  google_analytics id
google_verify: "https://www.googletagmanager.com/gtag/js?id=UA-126330089-2"
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
google-site-verification: google3643de2f0ecebcc4.html


